version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: maven
    steps:
      - checkout
  test:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn clean verify

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test

